name: Deploy

on:
  push:
    branches: 
      - main
    workflow_dispatch:

jobs:
  deploy:
    name: "Deploy to VPS"
    run: |
mkdir -p ~/.ssh/
echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key.pem chmod 600 ~/.ssh/deploy-key.pem
cat >> ~/.ssh/config <<END
8
9 jobs:
10
deploy:
11
12
13
name: "Deploy to VPS"
runs-on: ubuntu-latest
steps:
14
15
16
17
18
19
20
21
22
23
24
25
26
env:
27
28
29
30
31
32
Host my-vps
HostName $SSH_IP
User $SSH_USER
IdentityFile ~/.ssh/deploy-key.pem StrictHostKeyChecking no
END
SSH_USER: ${{ secrets.SSH_USER }}
SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} SSH_IP: ${{ secrets. SSH_IP }}
name: Print project root directory
run: ssh my-vps 'cd ${{ secrets. PROJECT_ROOT}} && pwd'
